# ios/Podfile

platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_install_all_ios_pods(flutter_application_path)
  eval(File.read(File.join(flutter_application_path, '.flutter-plugins-dependencies')), binding)
  system('flutter', 'pub', 'get')
  system('flutter', 'packages', 'pub', 'run', 'build_runner', 'build', '--delete-conflicting-outputs')
  flutter_application_path ||= File.expand_path('..', __FILE__)
  install! 'cocoapods', :warn_for_unused_master_specs_repo => false
  require File.expand_path(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb'), __FILE__)
  flutter_ios_podfile_setup
end

target 'Runner' do
  flutter_install_all_ios_pods(File.dirname(File.realpath(__FILE__)))

  # 👇 Add this block to enable camera/mic permissions in permission_handler
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
          '$(inherited)',
          'PERMISSION_CAMERA=1',
          'PERMISSION_MICROPHONE=1'
        ]
      end
    end
  end
end
